### ISSUE TITLE
The telegram iOS source code doesn't compile

### ISSUE THREAD

**Issue by ramgreenberg** [peter-iakovlev/Telegram#1]
Hey Peter,

Is there any chance you can help with running the new released source code of Telegram (http://telegram.org/resources/telegram_iphone.src.zip)

Thanks

**Comment by biloshkurskyi-ss** [comment]
Hi all,

please add clearing instruction how to run this project.

Because it contain some errors:

UFW (M iphoneos): ERROR: Build failed
Traceback (most recent call last):
  File "/Users/User_name/Library/Developer/Xcode/DerivedData/Telegraph-ekfedzvmlfvidudspiucukdmzqoj/Build/Intermediates/MtProtoKit.build/Debug-iphoneos/MtProtoKit iOS.build/Script-D05A831218AFB3F9007F1076.sh", line 812, in <module>
    run_build()
  File "/Users/User_name/Library/Developer/Xcode/DerivedData/Telegraph-ekfedzvmlfvidudspiucukdmzqoj/Build/Intermediates/MtProtoKit.build/Debug-iphoneos/MtProtoKit iOS.build/Script-D05A831218AFB3F9007F1076.sh", line 787, in run_build
    add_symlinks_to_framework(project)
  File "/Users/User_name/Library/Developer/Xcode/DerivedData/Telegraph-ekfedzvmlfvidudspiucukdmzqoj/Build/Intermediates/MtProtoKit.build/Debug-iphoneos/MtProtoKit iOS.build/Script-D05A831218AFB3F9007F1076.sh", line 675, in add_symlinks_to_framework
    attempt_symlink(os.path.join(base_dir, "Versions", "Current"), os.environ['FRAMEWORK_VERSION'])
  File "/Users/User_name/Library/Developer/Xcode/DerivedData/Telegraph-ekfedzvmlfvidudspiucukdmzqoj/Build/Intermediates/MtProtoKit.build/Debug-iphoneos/MtProtoKit iOS.build/Script-D05A831218AFB3F9007F1076.sh", line 493, in attempt_symlink
    os.stat(os.path.abspath(os.path.join(link_path, "..", link_to)))
OSError: [Errno 2] No such file or directory: '/Users/User_name/Library/Developer/Xcode/DerivedData/Telegraph-ekfedzvmlfvidudspiucukdmzqoj/Build/Products/Debug-iphoneos/MtProtoKit iOS.framework/Versions/A'
Command /bin/sh failed with exit code 1

**Comment by EdoEscada** [comment]
Thank you. I am also waiting for the guidance.

**Comment by Loag** [comment]
any news on this ?

**Comment by sh0seo** [comment]
+1

**Comment by ngothanhtai** [comment]
+1

**Comment by anjum-vervesys** [comment]
+1

**Comment by zmarty** [comment]
+1

**Comment by EdoEscada** [comment]
Yes +1 already compiled very well

**Comment by stackprogramer** [comment]
does anyone build this project successfully!!!!!
i could not

**Comment by bubakazouba** [comment]
+1

**Comment by ocalero** [comment]
You may think I'm an idiot... But, what does "+1" mean?

**Comment by zmarty** [comment]
@ocalero +1 is an informal upvote. It means "I have the same problem".

**Comment by ocalero** [comment]
Well, thank you for the explanation...... So +1!  Could anyone compile the telegram project?

**Comment by velmurugansubramaniam2** [comment]
Any one run this app, i am checking long time. +1

**Comment by rizwanshariq** [comment]
+1

**Comment by mohsenasm** [comment]
+1

**Comment by cloudjanak** [comment]
I can compile contact me.

**Comment by ahdidou-mohamed** [comment]
@ZetrixWeb-iOS would you please share your wise guidance with us here !

**Comment by janek** [comment]
+1

**Comment by MojtabaHs** [comment]
من کامپایل کردم و خیلی هم ساده بود.
اگر کسی خواست تماس بگیره

**Comment by Hecel85** [comment]
I've managed to compile the source code. If anyone needs help, contact me.

**Comment by riazrahaman** [comment]
@HassanEskandari  please share instructions on compiling the code

**Comment by Hecel85** [comment]
@riazrahaman I'll post instructions on how to do that, and maybe create a fork to get a source to compile with no errors soon.

**Comment by riazrahaman** [comment]
@HassanEskandari you could update the wiki with the instructions

**Comment by fabianeichinger** [comment]
I've worked out a few pretty straight forward steps to make this project compile:
[https://gist.github.com/feichngr/94bf7e7ce9af4b5c1dacfd82456367aa](https://gist.github.com/feichngr/94bf7e7ce9af4b5c1dacfd82456367aa)

**Comment by hieubtcoltech** [comment]
@HassanEskandari please share your instructions

**Comment by Hecel85** [comment]
@hieubtcoltech I was gonna write steps I've taken to make the project compile, but @fabulant did this before me and it is almost anything you need to do.
You can find it here https://gist.github.com/feichngr/94bf7e7ce9af4b5c1dacfd82456367aa

**Comment by fabianeichinger** [comment]
Ah, changed my github username and forgot to update the link. You can find the gist here:
https://gist.github.com/fabulant/94bf7e7ce9af4b5c1dacfd82456367aa
